// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonAPI.Context;

#nullable disable

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20220929000757_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HabilityPokemon", b =>
                {
                    b.Property<long>("HabilitiesIdHability")
                        .HasColumnType("bigint");

                    b.Property<long>("PokemonsIdPokemon")
                        .HasColumnType("bigint");

                    b.HasKey("HabilitiesIdHability", "PokemonsIdPokemon");

                    b.HasIndex("PokemonsIdPokemon");

                    b.ToTable("HabilityPokemon");
                });

            modelBuilder.Entity("PokemonAPI.Entities.Effect", b =>
                {
                    b.Property<long>("IdEffect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEffect"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEffect");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("PokemonAPI.Entities.Hability", b =>
                {
                    b.Property<long>("IdHability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdHability"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EffectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("IdHability");

                    b.HasIndex("EffectId");

                    b.HasIndex("TypeId");

                    b.ToTable("Habilities");
                });

            modelBuilder.Entity("PokemonAPI.Entities.Pokemon", b =>
                {
                    b.Property<long>("IdPokemon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPokemon"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPokemon");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokemonAPI.Entities.PokemonHability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("HabilityIdHability")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHability")
                        .HasColumnType("bigint");

                    b.Property<long>("IdPokemon")
                        .HasColumnType("bigint");

                    b.Property<long>("PokemonIdPokemon")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HabilityIdHability");

                    b.HasIndex("PokemonIdPokemon");

                    b.ToTable("PokemonHability");
                });

            modelBuilder.Entity("PokemonAPI.Entities.PokemonPokemonType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdPokemon")
                        .HasColumnType("bigint");

                    b.Property<long>("IdType")
                        .HasColumnType("bigint");

                    b.Property<long>("PokemonIdPokemon")
                        .HasColumnType("bigint");

                    b.Property<long>("PokemonTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PokemonIdPokemon");

                    b.HasIndex("PokemonTypeId");

                    b.ToTable("PokemonPokemonTypes");
                });

            modelBuilder.Entity("PokemonAPI.Entities.PokemonType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("PokemonPokemonType", b =>
                {
                    b.Property<long>("PokemonsIdPokemon")
                        .HasColumnType("bigint");

                    b.Property<long>("TypesId")
                        .HasColumnType("bigint");

                    b.HasKey("PokemonsIdPokemon", "TypesId");

                    b.HasIndex("TypesId");

                    b.ToTable("PokemonPokemonType");
                });

            modelBuilder.Entity("HabilityPokemon", b =>
                {
                    b.HasOne("PokemonAPI.Entities.Hability", null)
                        .WithMany()
                        .HasForeignKey("HabilitiesIdHability")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Entities.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("PokemonsIdPokemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonAPI.Entities.Hability", b =>
                {
                    b.HasOne("PokemonAPI.Entities.Effect", "Effect")
                        .WithMany("Habilities")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Entities.PokemonType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Effect");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PokemonAPI.Entities.PokemonHability", b =>
                {
                    b.HasOne("PokemonAPI.Entities.Hability", "Hability")
                        .WithMany()
                        .HasForeignKey("HabilityIdHability")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Entities.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonIdPokemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hability");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonAPI.Entities.PokemonPokemonType", b =>
                {
                    b.HasOne("PokemonAPI.Entities.Pokemon", "Pokemon")
                        .WithMany("pokemonPokemonTypes")
                        .HasForeignKey("PokemonIdPokemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Entities.PokemonType", "PokemonType")
                        .WithMany("pokemonPokemonType")
                        .HasForeignKey("PokemonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("PokemonType");
                });

            modelBuilder.Entity("PokemonPokemonType", b =>
                {
                    b.HasOne("PokemonAPI.Entities.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("PokemonsIdPokemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Entities.PokemonType", null)
                        .WithMany()
                        .HasForeignKey("TypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonAPI.Entities.Effect", b =>
                {
                    b.Navigation("Habilities");
                });

            modelBuilder.Entity("PokemonAPI.Entities.Pokemon", b =>
                {
                    b.Navigation("pokemonPokemonTypes");
                });

            modelBuilder.Entity("PokemonAPI.Entities.PokemonType", b =>
                {
                    b.Navigation("pokemonPokemonType");
                });
#pragma warning restore 612, 618
        }
    }
}
